
CREATE TABLE `web_timeline` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `custid` varchar(16) DEFAULT NULL COMMENT '客户号',
  `custnm` varchar(50) DEFAULT NULL COMMENT '客户名称',
  `custdate` varchar(20) DEFAULT NULL COMMENT '成为中行客户时间',
  `carddate` varchar(20) DEFAULT NULL COMMENT '第一张借记卡',
  `ccarddate` varchar(20) DEFAULT NULL COMMENT '第一张信用卡',
  `trandate` varchar(20) DEFAULT NULL COMMENT '第一笔信用卡交易',
  `tottran` varchar(50) DEFAULT NULL COMMENT '本年累计信用卡消费额',
  `totin` varchar(50) DEFAULT NULL COMMENT '本年进账资金总额',
  `totout` varchar(50) DEFAULT NULL COMMENT '本年出账资金总额',
  `totfee1` varchar(50) DEFAULT NULL COMMENT '本年累计话费',
  `totfee2` varchar(50) DEFAULT NULL COMMENT '本年累计燃气费',
  `totfee3` varchar(50) DEFAULT NULL COMMENT '本年累计水费',
  `totfee4` varchar(50) DEFAULT NULL COMMENT '本年',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8;

CREATE TABLE `web_customer` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `custid` varchar(16) DEFAULT NULL COMMENT '客户号',
  `custnm` varchar(50) DEFAULT NULL COMMENT '客户名称',
  `custnm1` varchar(20) DEFAULT NULL COMMENT '客户姓',
  `custnm2` varchar(30) DEFAULT NULL COMMENT '客户名',
  `pinyin` varchar(100) DEFAULT NULL COMMENT '姓名拼音',
  `title` varchar(30) DEFAULT NULL COMMENT '称谓',
  `idno` varchar(18) DEFAULT NULL COMMENT '身份证号',
  `education` varchar(30) DEFAULT NULL COMMENT '教育程度',
  `hmaddr1` varchar(20) DEFAULT NULL COMMENT '家庭地址1',
  `hmaddr2` varchar(20) DEFAULT NULL COMMENT '家庭地址2',
  `hmaddr3` varchar(30) DEFAULT NULL COMMENT '家庭地址3',
  `hmaddr4` varchar(100) DEFAULT NULL COMMENT '家庭地址4',
  `hmpost` varchar(10) DEFAULT NULL COMMENT '家庭地址邮编',
  `hmphone` varchar(20) DEFAULT NULL COMMENT '家庭电话',
  `mobile` varchar(30) DEFAULT NULL COMMENT '手机号码',
  `wkname` varchar(200) DEFAULT NULL COMMENT '单位名称',
  `wkadd1` varchar(20) DEFAULT NULL COMMENT '单位地址1',
  `wkadd2` varchar(20) DEFAULT NULL COMMENT '单位地址2',
  `wkadd3` varchar(30) DEFAULT NULL COMMENT '单位地址3',
  `wkadd4` varchar(100) DEFAULT NULL COMMENT '单位地址4',
  `wkpost` varchar(20) DEFAULT NULL COMMENT '单位邮编',
  `wkphone` varchar(30) DEFAULT NULL COMMENT '单位电话',
  `wktype` varchar(100) DEFAULT NULL COMMENT '行业性质',
  `ectype` varchar(100) DEFAULT NULL COMMENT '经济类型',
  `prolvl` varchar(100) DEFAULT NULL COMMENT '职位或职级',
  `wkyear` varchar(10) DEFAULT NULL COMMENT '现职工作时间（年）',
  `incom` varchar(20) DEFAULT NULL COMMENT '年收入总额',
  `age` varchar(10) DEFAULT NULL COMMENT '年龄',
  `childrens` varchar(10) DEFAULT NULL COMMENT '有无子女',
  `pronum` varchar(10) DEFAULT NULL COMMENT '产品持有种类（理财，基金，存款，信用卡，借记卡，贷款，网银，手机银行，贵金属）',
  `totasset` varchar(18) DEFAULT NULL COMMENT '总资产',
  `xpad` varchar(18) DEFAULT NULL COMMENT '理财',
  `fund` varchar(18) DEFAULT NULL COMMENT '基金',
  `invm` varchar(18) DEFAULT NULL COMMENT '存款',
  `ccard` varchar(10) DEFAULT NULL COMMENT '信用卡',
  `card` varchar(10) DEFAULT NULL COMMENT '借记卡',
  `borm` varchar(18) DEFAULT NULL COMMENT '贷款',
  `bocnet` varchar(10) DEFAULT NULL COMMENT '网银',
  `mobnet` varchar(10) DEFAULT NULL COMMENT '手机银行',
  `xpadg` varchar(10) DEFAULT NULL COMMENT '贵金属(有、无)',
  `cars` varchar(10) DEFAULT NULL COMMENT '车',
  `house` varchar(10) DEFAULT NULL COMMENT '房子',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;

CREATE TABLE `web_card` (
  `id` int(20) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `card_code` varchar(10) DEFAULT NULL COMMENT '卡片代码',
  `pro_name` varchar(200) DEFAULT NULL COMMENT '产品名称',
  `pro_introduct` text COMMENT '产品介绍',
  `pic_link` varchar(200) DEFAULT NULL COMMENT '图片链接',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8;

CREATE TABLE `web_cardapply` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `name1` varchar(10) DEFAULT NULL COMMENT '姓',
  `name2` varchar(20) DEFAULT NULL COMMENT '名',
  `pinyin` varchar(30) DEFAULT NULL COMMENT '拼音',
  `appellation` varchar(10) DEFAULT NULL COMMENT '称谓（先生，女士）',
  `passno` varchar(18) DEFAULT NULL COMMENT '身份证号',
  `education` varchar(50) DEFAULT NULL COMMENT '教育程度',
  `home_address1` varchar(100) DEFAULT NULL COMMENT '家庭地址1',
  `home_address2` varchar(100) DEFAULT NULL COMMENT '家庭地址2',
  `detail_add` varchar(100) DEFAULT NULL COMMENT '详细地址',
  `home_post` varchar(10) DEFAULT NULL COMMENT '住宅邮编',
  `residence_year` varchar(10) DEFAULT NULL COMMENT '现址住宅时间（年）',
  `residence_type` varchar(10) DEFAULT NULL COMMENT '住宅性质',
  `phone` varchar(20) DEFAULT NULL COMMENT '电话号码',
  `mobile_phone` varchar(11) DEFAULT NULL COMMENT '手机号码',
  `family_name_mum` varchar(10) DEFAULT NULL COMMENT '母亲姓氏',
  `wkname` varchar(50) DEFAULT NULL COMMENT '单位名称',
  `wk_address1` varchar(100) DEFAULT NULL COMMENT '单位地址1',
  `wk_address2` varchar(100) DEFAULT NULL COMMENT '单位地址2',
  `detail_wk_add` varchar(100) DEFAULT NULL COMMENT '详细地址',
  `wk_post` varchar(10) DEFAULT NULL COMMENT '单位邮编',
  `wk_phone` varchar(20) DEFAULT NULL COMMENT '单位电话',
  `profession_type` varchar(20) DEFAULT NULL COMMENT '行业性质',
  `economic_type` varchar(10) DEFAULT NULL COMMENT '经济类型',
  `title` varchar(50) DEFAULT NULL COMMENT '职位或职级',
  `worktime_year` varchar(10) DEFAULT NULL COMMENT '现职工作时间（年）',
  `tot_income` varchar(20) DEFAULT NULL COMMENT '年收入总额',
  `connection_person` varchar(50) DEFAULT NULL COMMENT '联系人',
  `relationship` varchar(50) DEFAULT NULL COMMENT '与申请人关系（父母，配偶，亲戚，其他）',
  `con_person_wkname` varchar(100) DEFAULT NULL COMMENT '联系人单位名称',
  `con_person_phone` varchar(20) DEFAULT NULL COMMENT '联系人电话',
  `con_person_mobile` varchar(11) DEFAULT NULL COMMENT '联系人手机号码',
  `account_send_type` varchar(50) DEFAULT NULL COMMENT '您的对账单发送方式选择（E-mail，手机）',
  `email` varchar(50) DEFAULT NULL COMMENT '电子邮箱',
  `send_address` varchar(100) DEFAULT NULL COMMENT '您的卡片等重要资料寄送地址（单位地址，家庭地址）',
  `need_pwd` varchar(10) DEFAULT NULL COMMENT '刷卡消费时是否需要密码',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
